[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "check_samarth_1120465"
client_id = "550369762865-c1ng6momc7dg4cq5kg04hfuqsnqf3ijc.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"  # fmt: skip